"""empty message

Revision ID: 07bfcc8c492c
Revises: 
Create Date: 2017-12-23 23:55:56.628525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07bfcc8c492c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', mysql.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
